In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.random.rand()

0.7579867070985494

In [5]:
np.random.randn() # normal (gauss) distribution

-0.5043187198212572

In [6]:
np.random.randn(4)

array([ 0.13146314,  0.14004567, -0.11734432, -0.31291598])

In [7]:
np.random.randn(4, 5)

array([[-1.08942992,  0.60783748, -0.39986976,  1.47467897, -0.02693463],
       [-1.27124118, -1.20843799,  0.6363934 ,  0.35050219, -0.50665694],
       [-0.11452925, -0.23294522, -1.00198192,  1.38451609,  1.7231242 ],
       [ 0.28593876,  0.33496277, -0.24150139,  0.02562702,  2.68169885]])

In [8]:
np.arange(0, 8, 2) # like range()

array([0, 2, 4, 6])

In [9]:
%timeit np.arange(0, 10000)
%timeit range(0, 10000)

100000 loops, best of 3: 12.9 µs per loop
10000 loops, best of 3: 129 µs per loop
